runtime: python310  # Specify your Python runtime
entrypoint: gunicorn -b :$PORT app:app  # Start command (using Gunicorn)

handlers:
  - url: /.*
    script: auto

env_variables:
  FLASK_ENV: production
  SECRET_KEY: "replace_this_with_a_secure_key"

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
